name: my-First-Workflow
on: push

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: Running Single Command in Job1
        run: echo "Hi this is my first workflow"
      - name: Checking OS Release
        run: cat /etc/os-release
      - name: Calling sleep
        run: sleep 20
  job2:
    name: JOB2
    runs-on: ubuntu-latest
    steps:
      - name: Checking the Hostname
        run: hostname
      - name: Running Multiple Commands
        run:
          echo "Hi from Costa Rica"
          echo "Current time is `date`"
  job3:
    name: JOB3
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Job with Single Dependency
        run: sleep 10
  job4:
    name: JOB4
    needs: [job1, job2, job3]
    runs-on: ubuntu-latest
    steps: 
      - name: Job for multiple dependencies
        run: sleep 10
